### ISSUE TITLE
QueryException: near 'thread = :thread': Error: 'thread' is not defined.

### ISSUE THREAD

**Issue by ianfp** [oroinc/crm#287]
Just upgraded to OroCRM 2.2.6 and got the error below when opening an email.

URL is `https://orocrm.gumstix.com/app.php/email/view/user-thread/163769?grid[user-email-grid]=i%3D1%26p%3D100%26s%255BreceivedAt%255D%3D1%26c%3Dmailbox0.contacts1.subject1.attachments1.receivedAt1%26v%3D__all__%26a%3Dgrid%26g%255BoriginalRoute%255D%3Doro_email_user_emails%26g%255BuserId%255D%3D47`

Stack trace:
```
Doctrine\ORM\Query\QueryException: SELECT e FROM Oro\Bundle\EmailBundle\Entity\Email e INNER JOIN e.emailUsers eu WHERE thread = :thread AND (eu.mailboxOwner IN(:mailboxes) OR eu.owner = :user) ORDER BY e.sentAt DESC
#62 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php(41): dqlError
#61 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(483): semanticalError
#60 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(585): processDeferredIdentificationVariables
#59 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(272): getAST
#58 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): parse
#57 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(281): _parse
#56 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(293): _doExecute
#55 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): executeIgnoreQueryCache
#54 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): execute
#53 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): getResult
#52 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Entity/Provider/EmailThreadProvider.php(159): getUserThreadEmails
#51 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Controller/EmailController.php(254): userThreadWidgetAction
#50 [Anonymous function](0): call_user_func_array
#49 /home/ubuntu/orocrm/app/bootstrap.php.cache(3196): handleRaw
#48 /home/ubuntu/orocrm/app/bootstrap.php.cache(3155): handle
#47 /home/ubuntu/orocrm/app/bootstrap.php.cache(3309): handle
#46 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php(85): render
#45 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php(136): render
#44 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php(76): render
#43 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/HttpKernelExtension.php(60): renderFragment
#42 /home/ubuntu/orocrm/app/cache/prod/twig/f8/f80214662b6c6677dcf2d87ad9fd780f5ed45fe5a7fb27c58bd31d0476f82d41.php(28): doDisplay
#41 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#40 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#39 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(417): render
#38 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Environment.php(362): render
#37 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/UIBundle/Twig/UiExtension.php(284): renderWidget
#36 /home/ubuntu/orocrm/app/cache/prod/twig/28/2881cc0b411ded650d1fc3014c2ad65fbad503c1ad4e1344a24b7f6db0997eea.php(35): block_content_data
#35 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#34 /home/ubuntu/orocrm/app/cache/prod/twig/ac/aca17542a576f37825aadc7a05e6ff4bd17ff8f5282ab63f7920cca51a88d1df.php(132): block_content
#33 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#32 /home/ubuntu/orocrm/app/cache/prod/twig/54/5482b4ed9f83817059ba40bbdde4b0a9825436c18f2849b5b65b3c04f26c1fa9.php(485): block_page_container
#31 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#30 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(279): renderBlock
#29 /home/ubuntu/orocrm/app/cache/prod/twig/54/5482b4ed9f83817059ba40bbdde4b0a9825436c18f2849b5b65b3c04f26c1fa9.php(146): doDisplay
#28 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#27 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#26 /home/ubuntu/orocrm/app/cache/prod/twig/d6/d6128c978b6792ee929f5decbdbe317822d25d83c1414772903f465c5cf11e2a.php(26): doDisplay
#25 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#24 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#23 /home/ubuntu/orocrm/app/cache/prod/twig/ac/aca17542a576f37825aadc7a05e6ff4bd17ff8f5282ab63f7920cca51a88d1df.php(41): doDisplay
#22 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#21 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#20 /home/ubuntu/orocrm/app/cache/prod/twig/d4/d4c474d7516f1ac699e71af0a02bc442a729e9ae45149fed0981776cf6aaccd1.php(37): doDisplay
#19 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#18 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#17 /home/ubuntu/orocrm/app/cache/prod/twig/28/2881cc0b411ded650d1fc3014c2ad65fbad503c1ad4e1344a24b7f6db0997eea.php(24): doDisplay
#16 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#15 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#14 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(417): render
#13 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php(50): render
#12 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(72): render
#11 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(97): renderResponse
#10 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/DelegatingEngine.php(57): renderResponse
#9 /home/ubuntu/orocrm/app/cache/prod/appProdProjectContainer.php(14): renderResponse
#8 /home/ubuntu/orocrm/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php(119): onKernelView
#7 [Anonymous function](0): call_user_func
#6 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(184): doDispatch
#5 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(46): dispatch
#4 /home/ubuntu/orocrm/app/bootstrap.php.cache(3199): handleRaw
#3 /home/ubuntu/orocrm/app/bootstrap.php.cache(3155): handle
#2 /home/ubuntu/orocrm/app/bootstrap.php.cache(3309): handle
#1 /home/ubuntu/orocrm/app/bootstrap.php.cache(2540): handle
#0 app.php(22): null
Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 85 near 'thread = :thread': Error: 'thread' is not defined.
#62 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php(63): semanticalError
#61 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(483): semanticalError
#60 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(585): processDeferredIdentificationVariables
#59 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(272): getAST
#58 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): parse
#57 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(281): _parse
#56 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(293): _doExecute
#55 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): executeIgnoreQueryCache
#54 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): execute
#53 /home/ubuntu/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): getResult
#52 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Entity/Provider/EmailThreadProvider.php(159): getUserThreadEmails
#51 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Controller/EmailController.php(254): userThreadWidgetAction
#50 [Anonymous function](0): call_user_func_array
#49 /home/ubuntu/orocrm/app/bootstrap.php.cache(3196): handleRaw
#48 /home/ubuntu/orocrm/app/bootstrap.php.cache(3155): handle
#47 /home/ubuntu/orocrm/app/bootstrap.php.cache(3309): handle
#46 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/InlineFragmentRenderer.php(85): render
#45 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php(136): render
#44 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/LazyLoadingFragmentHandler.php(76): render
#43 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/HttpKernelExtension.php(60): renderFragment
#42 /home/ubuntu/orocrm/app/cache/prod/twig/f8/f80214662b6c6677dcf2d87ad9fd780f5ed45fe5a7fb27c58bd31d0476f82d41.php(28): doDisplay
#41 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#40 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#39 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(417): render
#38 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Environment.php(362): render
#37 /home/ubuntu/orocrm/vendor/oro/platform/src/Oro/Bundle/UIBundle/Twig/UiExtension.php(284): renderWidget
#36 /home/ubuntu/orocrm/app/cache/prod/twig/28/2881cc0b411ded650d1fc3014c2ad65fbad503c1ad4e1344a24b7f6db0997eea.php(35): block_content_data
#35 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#34 /home/ubuntu/orocrm/app/cache/prod/twig/ac/aca17542a576f37825aadc7a05e6ff4bd17ff8f5282ab63f7920cca51a88d1df.php(132): block_content
#33 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#32 /home/ubuntu/orocrm/app/cache/prod/twig/54/5482b4ed9f83817059ba40bbdde4b0a9825436c18f2849b5b65b3c04f26c1fa9.php(485): block_page_container
#31 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(215): displayBlock
#30 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(279): renderBlock
#29 /home/ubuntu/orocrm/app/cache/prod/twig/54/5482b4ed9f83817059ba40bbdde4b0a9825436c18f2849b5b65b3c04f26c1fa9.php(146): doDisplay
#28 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#27 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#26 /home/ubuntu/orocrm/app/cache/prod/twig/d6/d6128c978b6792ee929f5decbdbe317822d25d83c1414772903f465c5cf11e2a.php(26): doDisplay
#25 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#24 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#23 /home/ubuntu/orocrm/app/cache/prod/twig/ac/aca17542a576f37825aadc7a05e6ff4bd17ff8f5282ab63f7920cca51a88d1df.php(41): doDisplay
#22 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#21 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#20 /home/ubuntu/orocrm/app/cache/prod/twig/d4/d4c474d7516f1ac699e71af0a02bc442a729e9ae45149fed0981776cf6aaccd1.php(37): doDisplay
#19 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#18 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#17 /home/ubuntu/orocrm/app/cache/prod/twig/28/2881cc0b411ded650d1fc3014c2ad65fbad503c1ad4e1344a24b7f6db0997eea.php(24): doDisplay
#16 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(438): displayWithErrorHandling
#15 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(406): display
#14 /home/ubuntu/orocrm/vendor/twig/twig/lib/Twig/Template.php(417): render
#13 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php(50): render
#12 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(72): render
#11 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/TwigEngine.php(97): renderResponse
#10 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/DelegatingEngine.php(57): renderResponse
#9 /home/ubuntu/orocrm/app/cache/prod/appProdProjectContainer.php(14): renderResponse
#8 /home/ubuntu/orocrm/vendor/sensio/framework-extra-bundle/EventListener/TemplateListener.php(119): onKernelView
#7 [Anonymous function](0): call_user_func
#6 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(184): doDispatch
#5 /home/ubuntu/orocrm/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(46): dispatch
#4 /home/ubuntu/orocrm/app/bootstrap.php.cache(3199): handleRaw
#3 /home/ubuntu/orocrm/app/bootstrap.php.cache(3155): handle
#2 /home/ubuntu/orocrm/app/bootstrap.php.cache(3309): handle
#1 /home/ubuntu/orocrm/app/bootstrap.php.cache(2540): handle
#0 app.php(22): null
```

**Comment by alexandr-parkhomenko** [comment]
Hi @ianfp,

Unfortunately we no longer support version 2.2.x anymore, please update your application to current release version to get fix.

**Comment by ianfp** [comment]
Oops! I didn't realize that 2.3 was out! Thank you!
