### ISSUE TITLE
QueryException when filtering "All Emails" by "From:"

### ISSUE THREAD

**Issue by ianfp** [oroinc/crm#289]
Using OroCRM 2.4.2, on page /app.php/email/user-emails, when I filter by the "From" field using the "contains" operator, I get the following error:

```
Doctrine\ORM\Query\QueryException: SELECT eu.id as _groupByPart0 FROM OroEmailBundle:EmailUser eu LEFT JOIN eu.folders f LEFT JOIN f.origin o WHERE o.isActive = true AND ((eu.owner = :owner AND eu.organization  = :organization) OR eu.mailboxOwner IN(:mailboxIds)) AND ((eu.owner = :owner AND eu.organization  = :organization) OR eu.mailboxOwner IN(:mailboxIds)) AND fromName LIKE :from1068717112 GROUP BY _groupByPart0
#31 vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php(41): dqlError
#30 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(448): syntaxError
#29 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2890): StringPrimary
#28 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2867): StringExpression
#27 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(3151): LikeExpression
#26 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2541): SimpleConditionalExpression
#25 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2447): ConditionalPrimary
#24 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2423): ConditionalFactor
#23 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2396): ConditionalTerm
#22 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2366): ConditionalExpression
#21 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1333): WhereClause
#20 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(876): SelectStatement
#19 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(843): QueryLanguage
#18 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(268): getAST
#17 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): parse
#16 vendor/oro/platform/src/Oro/Component/DoctrineUtils/ORM/QueryUtil.php(163): parseQuery
#15 vendor/oro/platform/src/Oro/Bundle/BatchBundle/ORM/Query/QueryCountCalculator.php(70): getCount
#14 vendor/oro/platform/src/Oro/Bundle/BatchBundle/ORM/Query/QueryCountCalculator.php(35): calculateCount
#13 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php(115): computeNbResult
#12 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php(160): init
#11 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/OrmPagerExtension.php(69): visitDatasource
#10 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Acceptor.php(36): acceptDatasource
#9 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(150): acceptDatasource
#8 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(140): getAcceptedDatasource
#7 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(87): getData
#6 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Controller/GridController.php(74): getAction
#5 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Controller/GridController.php(0): call_user_func_array
#4 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(144): handleRaw
#3 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(64): handle
#2 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): handle
#1 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): handle
#0 app.php(23): null
Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 331: Error: Expected '.' or '(', got 'fromName'
#31 vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php(52): syntaxError
#30 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(448): syntaxError
#29 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2890): StringPrimary
#28 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2867): StringExpression
#27 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(3151): LikeExpression
#26 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2541): SimpleConditionalExpression
#25 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2447): ConditionalPrimary
#24 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2423): ConditionalFactor
#23 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2396): ConditionalTerm
#22 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2366): ConditionalExpression
#21 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1333): WhereClause
#20 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(876): SelectStatement
#19 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(843): QueryLanguage
#18 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(268): getAST
#17 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): parse
#16 vendor/oro/platform/src/Oro/Component/DoctrineUtils/ORM/QueryUtil.php(163): parseQuery
#15 vendor/oro/platform/src/Oro/Bundle/BatchBundle/ORM/Query/QueryCountCalculator.php(70): getCount
#14 vendor/oro/platform/src/Oro/Bundle/BatchBundle/ORM/Query/QueryCountCalculator.php(35): calculateCount
#13 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php(115): computeNbResult
#12 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php(160): init
#11 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Pager/OrmPagerExtension.php(69): visitDatasource
#10 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Extension/Acceptor.php(36): acceptDatasource
#9 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(150): acceptDatasource
#8 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(140): getAcceptedDatasource
#7 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php(87): getData
#6 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Controller/GridController.php(74): getAction
#5 vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Controller/GridController.php(0): call_user_func_array
#4 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(144): handleRaw
#3 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(64): handle
#2 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): handle
#1 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): handle
#0 app.php(23): null
```

**Comment by NiMias** [comment]
Hello @ianfp!

You see, I couldn't reproduce this bug on the fresh installation of OroCRM application 2.4.2 version (PostgreSQL, PHP 7.1, Nginx, PHP-FPM).

Could you provide more specific Steps To Reproduce (how I can get this error)? Maybe you've made some customization? Also, please, provide your application environment description (DB type, PHP version, Web server type and version).

Thank you.

**Comment by manowark** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
